"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{spawnSync}=require("node:child_process");
const {readStatus,request,sql}=require("./helpers/localSupabase");
const {apiUrl,publishableKey,secretKey}=readStatus(); const password="risk008-local-password"; const made=[];
const admin=(p,o={})=>request(`${apiUrl}${p}`,{apikey:secretKey,token:secretKey,...o});
const rest=(p,t,o={})=>request(`${apiUrl}/rest/v1${p}`,{apikey:publishableKey,token:t,...o});
const key=n=>`80000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
async function user(label){const m=await admin("/auth/v1/admin/users",{method:"POST",body:{email:`risk008-${label}-${Date.now()}@local.test`,password,email_confirm:true}});assert.equal(m.status,200,JSON.stringify(m.body));made.push(m.body.id);const l=await request(`${apiUrl}/auth/v1/token?grant_type=password`,{apikey:publishableKey,method:"POST",body:{email:m.body.email,password}});return{id:m.body.id,token:l.body.access_token};}
const provenance=[{capability:"QUOTE",provider:"Fixture",source_observation:"REALTIME",venue_scope:"CONSOLIDATION_UNVERIFIED",interval:null,observed_at:"2026-09-18T12:00:00Z",delivery_state:"MISS",retrieved_at:"2026-09-18T12:00:01Z",original_retrieved_at:"2026-09-18T12:00:01Z",age_seconds:0,freshness_threshold_seconds:20,usable:true,entitlement_display:"PERMITTED_PRIVATE",entitlement_analysis:"PERMITTED_NON_RECONSTRUCTIVE",entitlement_storage:"PERMITTED_DERIVED_ONLY",entitlement_attribution:"NOT_REQUIRED_PRIVATE",entitlement_authority:"PLAN_DOCUMENTATION",entitlement_assessed_at:"2026-09-18T12:00:00Z",authority_reference:"plan:risk008-fixture",limitation_codes:["BROKER_VERIFICATION_REQUIRED","CONSOLIDATION_UNVERIFIED","NON_RECONSTRUCTIVE_ANALYTICS_ONLY","RAW_STORAGE_PROHIBITED"]},{capability:"HISTORY",provider:"Fixture",source_observation:"EOD",venue_scope:"UNKNOWN",interval:"1day",observed_at:"2026-09-17T12:00:00Z",delivery_state:"MISS",retrieved_at:"2026-09-18T12:00:01Z",original_retrieved_at:"2026-09-18T12:00:01Z",age_seconds:0,freshness_threshold_seconds:86400,usable:true,entitlement_display:"PROHIBITED",entitlement_analysis:"PERMITTED_NON_RECONSTRUCTIVE",entitlement_storage:"PERMITTED_DERIVED_ONLY",entitlement_attribution:"UNRESOLVED",entitlement_authority:"PUBLISHED_TERMS",entitlement_assessed_at:"2026-09-18T12:00:00Z",authority_reference:"terms:risk008-fixture",limitation_codes:["DISPLAY_PROHIBITED","ENTITLEMENT_UNRESOLVED","NON_RECONSTRUCTIVE_ANALYTICS_ONLY","RAW_STORAGE_PROHIBITED"]}];
const open=(k,stop="99",extra={})=>({p_idempotency_key:k,p_symbol:extra.symbol||"AAPL",p_market:"US",p_currency:"USD",p_analysis_contract_version:"risk008-test",p_analysis_created_at:"2026-09-18T12:00:00Z",p_thesis_text:"fixture",p_invalidation_condition:"fixture invalidation",p_planned_horizon:"swing",p_intended_invalidation_price:null,p_intended_target_price:null,p_maximum_planned_loss:null,p_risk_percentage:null,p_public_direction:"BULLISH",p_public_evidence_state:"SUPPORTIVE",p_public_risk_classification:"UNKNOWN",p_shariah_state:"COMPLIANT",p_provenance:provenance,p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T13:00:00Z",p_entry_price:extra.price||"100",p_entry_quantity:extra.quantity||"3",p_fees:extra.fees||"1",p_taxes:extra.taxes||"0",p_protective_stop:stop,p_stop_evidence:"OWNER_DECLARED"});
(async()=>{try{const a=await user("a"),b=await user("b");const now=new Date(Date.now()-60000).toISOString();const nyDay=sql("select (clock_timestamp() at time zone 'America/New_York')::date");
 const makeRiskUser=async(label,n)=>{const u=await user(label);for(const [endpoint,body] of [["create_personal_risk_policy_version",{p_client_idempotency_key:key(n),p_max_planned_loss_per_position_pct:"0.500000",p_max_aggregate_open_planned_loss_pct:"2.000000",p_daily_realized_gross_loss_limit_pct:"1.000000",p_weekly_realized_gross_loss_limit_pct:"2.500000",p_maximum_concurrent_open_positions:5,p_estimated_exit_slippage_bps:"25.0000"}],["create_broker_equity_snapshot",{p_client_idempotency_key:key(n+1),p_account_equity:"100000",p_currency:"USD",p_broker_identifier:"Fixture Broker",p_confirmation_method:"OWNER_CONFIRMED_BROKER_VALUE",p_confirmation_reference:`fixture:${label}-equity`,p_observed_at:now}],["create_broker_cost_schedule_version",{p_idempotency_key:key(n+2),p_effective_from:nyDay,p_evidence_reference:`fixture:${label}-schedule`,p_evidence_captured_at:now,p_broker_source_reference:`broker:${label}`,p_sec_source_reference:`sec:${label}`,p_finra_source_reference:`finra:${label}`,p_allowance_approval_reference:`founder:${label}`}]] ){const x=await rest(`/rpc/${endpoint}`,u.token,{method:"POST",body});assert.equal(x.status,200,JSON.stringify(x.body));}const opened=await rest("/rpc/create_risk_enforced_outcome_position",u.token,{method:"POST",body:open(key(n+3),"99",{symbol:`R${n}`,fees:"0"})});assert.equal(opened.body.accepted,true,JSON.stringify(opened.body));return{u,opened};};
 let r=await rest("/rpc/create_personal_risk_policy_version",a.token,{method:"POST",body:{p_client_idempotency_key:key(1),p_max_planned_loss_per_position_pct:"0.500000",p_max_aggregate_open_planned_loss_pct:"2.000000",p_daily_realized_gross_loss_limit_pct:"1.000000",p_weekly_realized_gross_loss_limit_pct:"2.500000",p_maximum_concurrent_open_positions:5,p_estimated_exit_slippage_bps:"25.0000"}});assert.equal(r.status,200,JSON.stringify(r.body));
 r=await rest("/rpc/create_broker_equity_snapshot",a.token,{method:"POST",body:{p_client_idempotency_key:key(2),p_account_equity:"100000",p_currency:"USD",p_broker_identifier:"Fixture Broker",p_confirmation_method:"OWNER_CONFIRMED_BROKER_VALUE",p_confirmation_reference:"fixture:risk008-equity",p_observed_at:now}});assert.equal(r.status,200,JSON.stringify(r.body));
 r=await rest("/rpc/create_broker_cost_schedule_version",a.token,{method:"POST",body:{p_idempotency_key:key(3),p_effective_from:nyDay,p_evidence_reference:"fixture:risk008-schedule",p_evidence_captured_at:now,p_broker_source_reference:"broker:risk008",p_sec_source_reference:"sec:risk008",p_finra_source_reference:"finra:risk008",p_allowance_approval_reference:"founder:risk008"}});assert.equal(r.status,200,JSON.stringify(r.body));
 const ledgerBefore=sql("select (select count(*) from public.outcome_decision_snapshots)||'|'||(select count(*) from public.outcome_snapshot_provenance)||'|'||(select count(*) from public.outcome_positions)||'|'||(select count(*) from public.outcome_position_events)||'|'||last_value||'|'||is_called from public.outcome_position_events_id_seq");
 const missing=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(4),null)});assert.equal(missing.status,200,JSON.stringify(missing.body));assert.equal(missing.body.accepted,false);assert.equal(missing.body.rejection_code,"MISSING_PROTECTIVE_STOP");
 assert.equal(sql("select (select count(*) from public.outcome_decision_snapshots)||'|'||(select count(*) from public.outcome_snapshot_provenance)||'|'||(select count(*) from public.outcome_positions)||'|'||(select count(*) from public.outcome_position_events)||'|'||last_value||'|'||is_called from public.outcome_position_events_id_seq"),ledgerBefore,"durable rejection validation changes neither ledger rows nor identity state");
 const malformedMissing=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:{...open(key(31),null),p_provenance:[{...provenance[0],raw_price:"100"},provenance[1]]}});assert.ok(!malformedMissing.ok);assert.equal(sql(`select count(*) from public.personal_risk_evaluations where user_id='${a.id}' and client_idempotency_key='${key(31)}'`),"0","ledger validation precedes durable missing-stop rejection");
 assert.equal(sql(`select modeled_sell_proceeds is null and close_commission is null and slippage_amount is null and raw_planned_loss is null and planned_loss_contribution is null from public.personal_risk_evaluations where id='${missing.body.evaluation_id}'`),"t");
 const replay=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(4),null)});assert.equal(replay.body.evaluation_id,missing.body.evaluation_id);assert.equal(replay.body.replayed,true);
 const reverseRecords=[...provenance].reverse(),reverseCodes=provenance.map(x=>({...x,limitation_codes:[...x.limitation_codes].reverse()})),reverseBoth=reverseRecords.map(x=>({...x,limitation_codes:[...x.limitation_codes].reverse()}));
 for(const p of [reverseRecords,reverseCodes,reverseBoth]){const x=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:{...open(key(4),null),p_provenance:p}});assert.equal(x.status,200,JSON.stringify(x.body));assert.equal(x.body.evaluation_id,missing.body.evaluation_id);assert.equal(x.body.replayed,true);}
 const semantic=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:{...open(key(4),null),p_provenance:provenance.map((x,i)=>i?x:{...x,provider:"Changed"})}});assert.equal(semantic.body.code,"23505");
 const missingAttempt=JSON.parse(sql(`select attempted_inputs::text from public.personal_risk_evaluations where id='${missing.body.evaluation_id}'`));
 for(const field of ["action","idempotency_key","posture","symbol","market","currency","analysis_contract_version","analysis_created_at","thesis_text","invalidation_condition","planned_horizon","intended_invalidation_price","intended_target_price","maximum_planned_loss","risk_percentage","public_direction","public_evidence_state","public_risk_classification","shariah_state","provenance","broker_confirmed","broker_effective_at","entry_price","entry_quantity","fees","taxes","protective_stop","protective_stop_evidence","ledger_request_fingerprint"])assert.ok(Object.hasOwn(missingAttempt,field),field);
 assert.equal(missingAttempt.protective_stop,null);assert.deepEqual(missingAttempt.provenance.map(x=>x.capability),["HISTORY","QUOTE"]);assert.deepEqual(missingAttempt.provenance[1].limitation_codes,[...missingAttempt.provenance[1].limitation_codes].sort());
 const successor=await rest("/rpc/create_broker_cost_schedule_version",a.token,{method:"POST",body:{p_idempotency_key:key(30),p_effective_from:nyDay,p_evidence_reference:"fixture:risk008-schedule-v2",p_evidence_captured_at:now,p_broker_source_reference:"broker:risk008-v2",p_sec_source_reference:"sec:risk008-v2",p_finra_source_reference:"finra:risk008-v2",p_allowance_approval_reference:"founder:risk008-v2"}});assert.equal(successor.status,200,JSON.stringify(successor.body));const historicalReplay=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(4),null)});assert.equal(historicalReplay.body.cost_schedule_version_id,missing.body.cost_schedule_version_id);assert.notEqual(successor.body[0].schedule_version_id,missing.body.cost_schedule_version_id);
 assert.equal((await rest("/rpc/create_broker_cost_schedule_version",a.token,{method:"POST",body:{p_idempotency_key:key(30),p_effective_from:nyDay,p_evidence_reference:"fixture:risk008-schedule-CHANGED",p_evidence_captured_at:now,p_broker_source_reference:"broker:risk008-v2",p_sec_source_reference:"sec:risk008-v2",p_finra_source_reference:"finra:risk008-v2",p_allowance_approval_reference:"founder:risk008-v2"}})).body.code,"23505");
 for(const clause of ["modeled_sell_proceeds=0","attempted_protective_stop=99","observed_stop_presence=true","modeled_sell_proceeds=1,close_commission=null"]){assert.equal(sql(`do $q$ begin begin update public.personal_risk_evaluations set ${clause} where id='${missing.body.evaluation_id}'; raise exception 'accepted'; exception when check_violation then null; end; end $q$; select 'refused'`),"refused");}
 const ok=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(5),"99")});assert.equal(ok.status,200,JSON.stringify(ok.body));assert.equal(ok.body.accepted,true);assert.equal(sql(`select slippage_amount from public.personal_risk_evaluations where id='${ok.body.evaluation_id}'`),"0.74250000");
 assert.equal(sql(`select attempted_inputs->>'ledger_request_fingerprint'=(select request_fingerprint from public.outcome_positions where id='${ok.body.position_id}') from public.personal_risk_evaluations where id='${ok.body.evaluation_id}'`),"t","Migration 004 and 008 share the canonical ledger fingerprint");
 assert.deepEqual(JSON.parse(sql(`select (attempted_inputs->'provenance')::text from public.personal_risk_evaluations where id='${ok.body.evaluation_id}'`)),missingAttempt.provenance,"Migration 008 canonical provenance is stable across rejected and Migration 004-backed accepted opens");
 assert.equal(ok.body.cost_schedule_version_id,successor.body[0].schedule_version_id,"new evaluation selects latest applicable schedule");
 assert.equal(sql(`do $q$ begin begin update public.personal_risk_evaluations set close_commission=null where id='${ok.body.evaluation_id}'; raise exception 'accepted'; exception when check_violation then null; end; end $q$;select 'refused'`),"refused");
 const increase=await rest("/rpc/increase_risk_enforced_position",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(6),p_broker_effective_at:"2026-09-18T14:00:00Z",p_added_quantity:"2",p_added_entry_price:"110",p_entry_fee:"1",p_entry_tax:"0.5"}});assert.equal(increase.status,200,JSON.stringify(increase.body));assert.equal(increase.body.accepted,true);assert.equal(sql(`select remaining_quantity||'|'||weighted_entry_price||'|'||remaining_entry_fee_pool||'|'||remaining_entry_tax_pool from public.outcome_position_risk_state where position_id='${ok.body.position_id}'`),"5.00000000|104.00000000|2.00000000|0.50000000");
 const increaseBody={p_position_id:ok.body.position_id,p_idempotency_key:key(6),p_broker_effective_at:"2026-09-18T14:00:00Z",p_added_quantity:"2",p_added_entry_price:"110",p_entry_fee:"1",p_entry_tax:"0.5"};const increaseReplay=await rest("/rpc/increase_risk_enforced_position",a.token,{method:"POST",body:increaseBody});assert.equal(increaseReplay.body.evaluation_id,increase.body.evaluation_id);assert.equal(increaseReplay.body.increase_id,increase.body.increase_id);assert.equal(increaseReplay.body.replayed,true);
 assert.equal((await rest("/rpc/increase_risk_enforced_position",a.token,{method:"POST",body:{...increaseBody,p_added_quantity:"1"}})).body.code,"23505");
 assert.deepEqual(Object.keys(JSON.parse(sql(`select attempted_inputs::text from public.personal_risk_evaluations where id='${increase.body.evaluation_id}'`))).sort(),["action","added_entry_price","added_quantity","broker_effective_at","entry_fee","entry_tax","idempotency_key","position_id"].sort());
 const increase2Body={p_position_id:ok.body.position_id,p_idempotency_key:key(32),p_broker_effective_at:"2026-09-18T14:30:00Z",p_added_quantity:"1",p_added_entry_price:"104",p_entry_fee:"0.5",p_entry_tax:"0.25"};const increase2=await rest("/rpc/increase_risk_enforced_position",a.token,{method:"POST",body:increase2Body});assert.equal(increase2.status,200,JSON.stringify(increase2.body));assert.equal(increase2.body.accepted,true);assert.equal(sql(`select remaining_quantity||'|'||weighted_entry_price||'|'||remaining_entry_fee_pool||'|'||remaining_entry_tax_pool from public.outcome_position_risk_state where position_id='${ok.body.position_id}'`),"6.00000000|104.00000000|2.50000000|0.75000000");const increase2Replay=await rest("/rpc/increase_risk_enforced_position",a.token,{method:"POST",body:increase2Body});assert.equal(increase2Replay.body.evaluation_id,increase2.body.evaluation_id);assert.equal(increase2Replay.body.increase_id,increase2.body.increase_id);assert.equal(increase2Replay.body.replayed,true);
 const tight=await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(7),p_new_stop:"100",p_evidence_class:"BROKER_CONFIRMED"}});assert.equal(tight.status,200,JSON.stringify(tight.body));assert.equal(tight.body.direction,"TIGHTENING");
 assert.equal((await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(7),p_new_stop:"101",p_evidence_class:"BROKER_CONFIRMED"}})).body.code,"23505");
 const noOp=await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(8),p_new_stop:"100",p_evidence_class:"OWNER_DECLARED"}});assert.ok(!noOp.ok);
 const loose=await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(9),p_new_stop:"99",p_evidence_class:"OWNER_DECLARED"}});assert.equal(loose.status,200,JSON.stringify(loose.body));assert.equal(loose.body.accepted,true);
 const looseReplay=await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(9),p_new_stop:"99",p_evidence_class:"OWNER_DECLARED"}});assert.equal(looseReplay.body.evaluation_id,loose.body.evaluation_id);assert.equal(looseReplay.body.stop_change_id,loose.body.stop_change_id);assert.equal(looseReplay.body.replayed,true);
 assert.equal((await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(9),p_new_stop:"98",p_evidence_class:"OWNER_DECLARED"}})).body.code,"23505");
 assert.deepEqual(Object.keys(JSON.parse(sql(`select attempted_inputs::text from public.personal_risk_evaluations where id='${loose.body.evaluation_id}'`))).sort(),["action","evidence_class","idempotency_key","new_stop","position_id"].sort());
 const partial=await rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(10),p_event_type:"PARTIAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T15:00:00Z",p_price:"120",p_quantity:"2",p_fees:"0.4",p_taxes:"0.1"}});assert.equal(partial.status,200,JSON.stringify(partial.body));assert.equal(partial.body.allocated_entry_fee,0.83333333);assert.equal(partial.body.allocated_entry_tax,0.25);assert.equal(partial.body.realized_pnl,30.41666667);
 const partialReplay=await rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(10),p_event_type:"PARTIAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T15:00:00Z",p_price:"120",p_quantity:"2",p_fees:"0.4",p_taxes:"0.1"}});assert.equal(partialReplay.body.event_id,partial.body.event_id);assert.equal(partialReplay.body.replayed,true);
 assert.equal((await rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(10),p_event_type:"PARTIAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T15:00:00Z",p_price:"121",p_quantity:"2",p_fees:"0.4",p_taxes:"0.1"}})).body.code,"23505");
 const crossCalls={
  open:k=>rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(k,null,{symbol:"CROSS"})}),
  event:k=>rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:k,p_event_type:"OWNER_NOTE",p_broker_confirmed:false,p_owner_note:"cross-key probe"}}),
  increase:k=>rest("/rpc/increase_risk_enforced_position",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:k,p_broker_effective_at:"2026-09-18T15:00:00Z",p_added_quantity:"1",p_added_entry_price:"100",p_entry_fee:"0",p_entry_tax:"0"}}),
  stop:k=>rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:k,p_new_stop:"98",p_evidence_class:"OWNER_DECLARED"}})
 };
 for(const [source,k,targets] of [["accepted open",key(5),["event","increase","stop"]],["missing-stop",key(4),["event","increase","stop"]],["event",key(10),["open","increase","stop"]],["increase",key(6),["open","event","stop"]],["stop",key(9),["open","event","increase"]]])for(const target of targets){const x=await crossCalls[target](k);assert.equal(x.body.code,"23505",`${source} -> ${target}: ${JSON.stringify(x.body)}`);}
 assert.equal(sql(`select ny_day||'|'||ny_week from public.outcome_exit_cost_allocations where event_id=${partial.body.event_id}`),"2026-09-18|2026-09-14");
 const final=await rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:ok.body.position_id,p_idempotency_key:key(11),p_event_type:"FINAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T16:00:00Z",p_price:"100",p_quantity:"4",p_fees:"0.6",p_taxes:"0.2"}});assert.equal(final.status,200,JSON.stringify(final.body));assert.equal(sql(`select remaining_quantity||'|'||remaining_entry_fee_pool||'|'||remaining_entry_tax_pool from public.outcome_position_risk_state where position_id='${ok.body.position_id}'`),"0.00000000|0.00000000|0.00000000");
 assert.equal(sql(`select sum(gross_realized_loss)=greatest(0,-min(realized_pnl)) and max(realized_pnl)>0 and min(realized_pnl)<0 from public.outcome_exit_cost_allocations where position_id='${ok.body.position_id}'`),"t","winner never offsets same-day/week gross loss regardless of row order");
 const rejected=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(12),"90",{symbol:"LOSS",quantity:"100",fees:"0"})});assert.equal(rejected.status,200,JSON.stringify(rejected.body));assert.equal(rejected.body.accepted,false);assert.equal(rejected.body.rejection_code,"PER_POSITION_PLANNED_LOSS_LIMIT");
 const mappings={MISSING_PROTECTIVE_STOP:"PROTECTIVE_STOP_REQUIRED",PER_POSITION_PLANNED_LOSS_LIMIT:"PER_POSITION_PLANNED_LOSS",AGGREGATE_OPEN_PLANNED_LOSS_LIMIT:"AGGREGATE_OPEN_PLANNED_LOSS",DAILY_GROSS_REALIZED_LOSS_LIMIT:"DAILY_GROSS_REALIZED_LOSS",WEEKLY_GROSS_REALIZED_LOSS_LIMIT:"WEEKLY_GROSS_REALIZED_LOSS",MAXIMUM_CONCURRENT_POSITIONS:"MAXIMUM_CONCURRENT_POSITIONS"};const kinds=Object.values(mappings);
 for(const [code,correct] of Object.entries(mappings))for(const kind of kinds.filter(x=>x!==correct))assert.equal(sql(`do $q$ begin begin update public.personal_risk_evaluations set rejection_code='${code}',threshold_kind='${kind}' where id='${rejected.body.evaluation_id}';raise exception 'accepted';exception when check_violation then null;end;end $q$;select 'refused'`),"refused",`${code}/${kind}`);
 assert.equal(sql(`do $q$ begin begin update public.personal_risk_evaluations set threshold_kind='PER_POSITION_PLANNED_LOSS' where id='${ok.body.evaluation_id}';raise exception 'accepted';exception when check_violation then null;end;end $q$;select 'refused'`),"refused","accepted rows cannot claim a rejection threshold");
 const beforeBounds=Number(sql(`select count(*) from public.personal_risk_evaluations where user_id='${a.id}'`));
 const overQ=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(13),"1",{symbol:"OVERQ",quantity:"10000.00000001",fees:"0"})});assert.equal(overQ.body.code,"P8011");
 const overP=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(14),"100000.00000001",{symbol:"OVERP",quantity:"1",fees:"0"})});assert.equal(overP.body.code,"P8010");
 assert.equal(Number(sql(`select count(*) from public.personal_risk_evaluations where user_id='${a.id}'`)),beforeBounds,"raised schedule preconditions write no evidence");
 const exactQ=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(15),"1",{symbol:"EXQ",quantity:"10000",fees:"0"})});assert.equal(exactQ.status,200);assert.equal(exactQ.body.rejection_code,"PER_POSITION_PLANNED_LOSS_LIMIT");
 const exactP=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(16),"100000",{symbol:"EXP",quantity:"1",fees:"0"})});assert.equal(exactP.status,200,JSON.stringify(exactP.body));assert.equal(exactP.body.accepted,true);
 await rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:exactP.body.position_id,p_idempotency_key:key(17),p_event_type:"FINAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T16:00:00Z",p_price:"100",p_quantity:"1",p_fees:"0",p_taxes:"0"}});
 const concurrent=await Promise.all(Array.from({length:6},(_,i)=>rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(20+i),"100",{symbol:`C${i}`,fees:"0"})})));assert.ok(concurrent.every(x=>x.status===200),JSON.stringify(concurrent));assert.equal(concurrent.filter(x=>x.body.accepted).length,5);assert.equal(concurrent.filter(x=>x.body.rejection_code==="MAXIMUM_CONCURRENT_POSITIONS").length,1);assert.equal(sql(`select count(*) from public.outcome_position_risk_state where user_id='${a.id}' and remaining_quantity>0`),"5");
 const cuser=await user("aggregate");
 for(const [endpoint,body] of [["create_personal_risk_policy_version",{p_client_idempotency_key:key(60),p_max_planned_loss_per_position_pct:"0.500000",p_max_aggregate_open_planned_loss_pct:"2.000000",p_daily_realized_gross_loss_limit_pct:"1.000000",p_weekly_realized_gross_loss_limit_pct:"2.500000",p_maximum_concurrent_open_positions:5,p_estimated_exit_slippage_bps:"25.0000"}],["create_broker_equity_snapshot",{p_client_idempotency_key:key(61),p_account_equity:"100000",p_currency:"USD",p_broker_identifier:"Fixture Broker",p_confirmation_method:"OWNER_CONFIRMED_BROKER_VALUE",p_confirmation_reference:"fixture:risk008-aggregate",p_observed_at:now}],["create_broker_cost_schedule_version",{p_idempotency_key:key(62),p_effective_from:nyDay,p_evidence_reference:"fixture:risk008-aggregate-schedule",p_evidence_captured_at:now,p_broker_source_reference:"broker:aggregate",p_sec_source_reference:"sec:aggregate",p_finra_source_reference:"finra:aggregate",p_allowance_approval_reference:"founder:aggregate"}]]){const x=await rest(`/rpc/${endpoint}`,cuser.token,{method:"POST",body});assert.equal(x.status,200,JSON.stringify(x.body));}
 const seed=await rest("/rpc/create_risk_enforced_outcome_position",cuser.token,{method:"POST",body:open(key(63),"99",{symbol:"AGG0",fees:"0"})});assert.equal(seed.body.accepted,true);sql(`update public.outcome_position_risk_state set current_planned_loss_contribution=1990 where position_id='${seed.body.position_id}'`);
 const aggregateRace=await Promise.all([64,65].map((n,i)=>rest("/rpc/create_risk_enforced_outcome_position",cuser.token,{method:"POST",body:open(key(n),"99",{symbol:`AGG${i+1}`,fees:"0"})})));assert.equal(aggregateRace.filter(x=>x.body.accepted).length,1,JSON.stringify(aggregateRace));assert.equal(aggregateRace.filter(x=>x.body.rejection_code==="AGGREGATE_OPEN_PLANNED_LOSS_LIMIT").length,1,JSON.stringify(aggregateRace));assert.ok(Number(sql(`select sum(current_planned_loss_contribution) from public.outcome_position_risk_state where user_id='${cuser.id}' and remaining_quantity>0`))<=2000);
 const differentActionRace=await Promise.all([rest("/rpc/create_risk_enforced_outcome_position",cuser.token,{method:"POST",body:open(key(66),null,{symbol:"KEYRACE"})}),rest("/rpc/create_broker_cost_schedule_version",cuser.token,{method:"POST",body:{p_idempotency_key:key(66),p_effective_from:nyDay,p_evidence_reference:"fixture:key-race-schedule",p_evidence_captured_at:now,p_broker_source_reference:"broker:key-race",p_sec_source_reference:"sec:key-race",p_finra_source_reference:"finra:key-race",p_allowance_approval_reference:"founder:key-race"}})]);assert.equal(differentActionRace.filter(x=>x.status===200).length,1,JSON.stringify(differentActionRace));assert.equal(differentActionRace.filter(x=>x.body.code==="23505").length,1,JSON.stringify(differentActionRace));assert.equal(Number(sql(`select (select count(*) from public.personal_risk_evaluations where user_id='${cuser.id}' and client_idempotency_key='${key(66)}')+(select count(*) from public.broker_cost_schedule_versions where user_id='${cuser.id}' and client_idempotency_key='${key(66)}')`)),1);
 const nyWeek=sql("select date_trunc('week',clock_timestamp() at time zone 'America/New_York')::date");sql(`update public.outcome_exit_cost_allocations set gross_realized_loss=1000,ny_day='${nyDay}',ny_week='${nyWeek}' where event_id=${partial.body.event_id}`);const dailyBlocked=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(40),"100",{symbol:"DAY",fees:"0"})});assert.equal(dailyBlocked.body.rejection_code,"DAILY_GROSS_REALIZED_LOSS_LIMIT");
 sql(`update public.outcome_exit_cost_allocations set gross_realized_loss=2500,ny_day=('${nyDay}'::date-1),ny_week='${nyWeek}' where event_id=${partial.body.event_id}`);const weeklyBlocked=await rest("/rpc/create_risk_enforced_outcome_position",a.token,{method:"POST",body:open(key(41),"100",{symbol:"WEEK",fees:"0"})});assert.equal(weeklyBlocked.body.rejection_code,"WEEKLY_GROSS_REALIZED_LOSS_LIMIT");
 const reducingTarget=concurrent.find(x=>x.body.accepted).body.position_id;sql(`update public.outcome_position_risk_state set current_planned_loss_contribution=500 where user_id='${a.id}' and remaining_quantity>0`);sql(`update public.outcome_exit_cost_allocations set gross_realized_loss=3000,ny_day='${nyDay}',ny_week='${nyWeek}' where event_id=${partial.body.event_id}`);
 const gateTight=await rest("/rpc/change_outcome_protective_stop",a.token,{method:"POST",body:{p_position_id:reducingTarget,p_idempotency_key:key(42),p_new_stop:"101",p_evidence_class:"OWNER_DECLARED"}});assert.equal(gateTight.status,200,JSON.stringify(gateTight.body));assert.equal(gateTight.body.direction,"TIGHTENING");
 const gateExit=await rest("/rpc/append_risk_lifecycle_event",a.token,{method:"POST",body:{p_position_id:reducingTarget,p_idempotency_key:key(43),p_event_type:"FINAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T17:00:00Z",p_price:"100",p_quantity:"3",p_fees:"0",p_taxes:"0"}});assert.equal(gateExit.status,200,JSON.stringify(gateExit.body));
 assert.equal((await rest("/personal_risk_evaluations?select=id",b.token)).body.length,0);assert.ok((await rest("/personal_risk_evaluations",a.token,{method:"POST",body:{}})).status>=400);
 const calc=sql("select allowance_selected from public._risk008_calculate(3,100,4844.90291262,0,0,25)");assert.equal(calc,"0.50000000");
 assert.equal(sql("select allowance_selected from public._risk008_calculate(3,100,4844.90270000,0,0,25)"),"0.50000000","nearest observable value below crossover uses floor");
 assert.equal(sql("select allowance_selected>allowance_floor from public._risk008_calculate(3,100,4844.90310000,0,0,25)"),"t","nearest observable value above crossover uses formula");
 assert.equal(sql("select allowance_selected from public._risk008_calculate(1538,1,0.00000001,0,0,25)"),"0.50000000");assert.equal(sql("select allowance_selected from public._risk008_calculate(1539,1,0.00000001,0,0,25)"),"0.50010500");
 assert.equal(sql("select close_commission from public._risk008_calculate(1,1,100,0,0,25)"),"1.00000000");assert.equal(sql("select close_commission from public._risk008_calculate(1,1,2000,0,0,25)"),"1.60000000");
 assert.equal(sql("select string_agg((x at time zone 'America/New_York')::date||'|'||date_trunc('week',x at time zone 'America/New_York')::date,',' order by x) from unnest(array['2026-03-08T06:59:59Z'::timestamptz,'2026-03-08T07:00:00Z'::timestamptz,'2025-11-02T05:30:00Z'::timestamptz,'2025-11-02T06:30:00Z'::timestamptz]) x"),"2025-11-02|2025-10-27,2025-11-02|2025-10-27,2026-03-08|2026-03-02,2026-03-08|2026-03-02");
 for(const [label,n,remove] of [["no-policy",100,["personal_risk_policy_versions"]],["no-equity",110,["daily_risk_equity_bases","weekly_risk_equity_bases","broker_equity_snapshots"]],["no-daily",120,["daily_risk_equity_bases"]],["no-weekly",130,["weekly_risk_equity_bases"]],["no-cost",140,["broker_cost_schedule_components","broker_cost_schedule_versions"]]]){
  const {u,opened}=await makeRiskUser(label,n);sql(`delete from public.personal_risk_evaluations where user_id='${u.id}'`);for(const table of remove)sql(`delete from public.${table} where user_id='${u.id}'`);
  const tightening=await rest("/rpc/change_outcome_protective_stop",u.token,{method:"POST",body:{p_position_id:opened.body.position_id,p_idempotency_key:key(n+4),p_new_stop:"100",p_evidence_class:"OWNER_DECLARED"}});assert.equal(tightening.status,200,`${label} tightening: ${JSON.stringify(tightening.body)}`);assert.equal(tightening.body.direction,"TIGHTENING");
  const exit=await rest("/rpc/append_risk_lifecycle_event",u.token,{method:"POST",body:{p_position_id:opened.body.position_id,p_idempotency_key:key(n+5),p_event_type:"FINAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T16:00:00Z",p_price:"100",p_quantity:"3",p_fees:"0",p_taxes:"0"}});assert.equal(exit.status,200,`${label} exit: ${JSON.stringify(exit.body)}`);
 }
 for(const [label,n,gate] of [["max-capacity",160,"max"],["aggregate-breached",180,"aggregate"],["daily-breached",200,"daily"],["weekly-breached",220,"weekly"]]){
  const {u,opened}=await makeRiskUser(label,n);
  if(gate==="max")for(let i=0;i<4;i++){const x=await rest("/rpc/create_risk_enforced_outcome_position",u.token,{method:"POST",body:open(key(n+6+i),"99",{symbol:`M${n+i}`,fees:"0"})});assert.equal(x.body.accepted,true,JSON.stringify(x.body));}
  if(gate==="aggregate")sql(`update public.outcome_position_risk_state set current_planned_loss_contribution=2500 where position_id='${opened.body.position_id}'`);
  if(gate==="daily"||gate==="weekly"){const other=await rest("/rpc/create_risk_enforced_outcome_position",u.token,{method:"POST",body:open(key(n+6),"99",{symbol:`L${n}`,fees:"0"})});assert.equal(other.body.accepted,true);const loss=await rest("/rpc/append_risk_lifecycle_event",u.token,{method:"POST",body:{p_position_id:other.body.position_id,p_idempotency_key:key(n+7),p_event_type:"FINAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T15:00:00Z",p_price:"90",p_quantity:"3",p_fees:"0",p_taxes:"0"}});assert.equal(loss.status,200);sql(`update public.outcome_exit_cost_allocations set gross_realized_loss=${gate==="daily"?1000:2500},ny_day=${gate==="daily"?`'${nyDay}'`:`'${nyDay}'::date-1`},ny_week='${nyWeek}' where event_id=${loss.body.event_id}`);}
  const tightening=await rest("/rpc/change_outcome_protective_stop",u.token,{method:"POST",body:{p_position_id:opened.body.position_id,p_idempotency_key:key(n+20),p_new_stop:"100",p_evidence_class:"OWNER_DECLARED"}});assert.equal(tightening.status,200,`${label} tightening: ${JSON.stringify(tightening.body)}`);
  const exit=await rest("/rpc/append_risk_lifecycle_event",u.token,{method:"POST",body:{p_position_id:opened.body.position_id,p_idempotency_key:key(n+21),p_event_type:"FINAL_EXIT_CONFIRMED",p_broker_confirmed:true,p_broker_effective_at:"2026-09-18T16:00:00Z",p_price:"100",p_quantity:"3",p_fees:"0",p_taxes:"0"}});assert.equal(exit.status,200,`${label} exit: ${JSON.stringify(exit.body)}`);
 }
 const downPath=path.resolve(__dirname,"../../db/down-migrations/20260919120000_008_personal_risk_lifecycle.sql");const refusal=spawnSync(process.execPath,["-e",`const fs=require('fs');const {sql}=require('./tests/helpers/localSupabase');sql(fs.readFileSync(process.argv[1],'utf8'))`,downPath],{cwd:path.resolve(__dirname,".."),encoding:"utf8"});assert.notEqual(refusal.status,0);assert.match(`${refusal.stdout}${refusal.stderr}`,/reversal refused: immutable risk lifecycle evidence exists/);assert.equal(sql("select count(*) from pg_class where oid='public.personal_risk_evaluations'::regclass"),"1");
 console.log("Migration 008 missing-stop, arithmetic, replay and RLS contracts passed.");
}finally{for(const id of made){for(const table of ["personal_risk_evaluations","outcome_exit_cost_allocations","outcome_protective_stop_changes","outcome_position_increases","outcome_position_risk_state","outcome_position_events","outcome_positions","outcome_snapshot_provenance","outcome_decision_snapshots","broker_cost_schedule_components","broker_cost_schedule_versions","daily_risk_equity_bases","weekly_risk_equity_bases","broker_equity_snapshots","personal_risk_policy_versions"])sql(`delete from public.${table} where user_id='${id}'`);await admin(`/auth/v1/admin/users/${id}`,{method:"DELETE"});}}})().catch(e=>{console.error(e);process.exit(1)});
