import { beforeEach, describe, expect, it, vi } from "vitest";
const { get, post }=vi.hoisted(()=>({get:vi.fn(),post:vi.fn()}));
vi.mock("./api",()=>({api:{get,post}}));
import { createCostSchedule, createEquitySnapshot, createPolicyVersion, getPersonalRiskStatus, PersonalRiskClientError, validateStatusResponse } from "./personalRisk";

const ID="123e4567-e89b-42d3-a456-426614174000";
const component=(code:string)=>({id:ID,schedule_id:ID,component_code:code,evidence_class:"REGULATOR_PUBLISHED",application_mode:"REFERENCE",proceeds_rate:null,quantity_rate:null,minimum_amount:null,maximum_amount:null,fixed_amount:null,source_authority:"authority",source_reference:"https://example.com",source_effective_from:"2026-01-01",evidence_limitations:"none"});
const status={success:true,data:{observation:{instant:"2026-09-22T00:00:00Z",newYorkDate:"2026-09-21",newYorkWeek:"2026-09-21"},policyVersion:null,costSchedule:{id:ID,version_no:"1",broker_legal_entity:"Saxo Bank",pricing_tier:"Classic",account_currency:"USD",instrument_scope:"LONG_US_LISTED_CASH_EQUITY",effective_from:"2026-09-19",effective_through:null,maximum_modeled_sell_proceeds:"100000",maximum_modeled_exit_quantity:"10000",evidence_reference:"evidence",evidence_captured_at:"2026-09-18T21:00:43Z",created_at:"2026-09-22T00:00:00Z",components:[component("CLOSE_COMMISSION"),component("FINRA_TAF_REFERENCE"),component("REGULATORY_ALLOWANCE"),component("SEC_REFERENCE")]},equitySnapshot:null,dailyBasis:null,weeklyBasis:null,bootstrapComplete:false,pendingIntent:null}};
describe("personal-risk authenticated service",()=>{beforeEach(()=>{get.mockReset();post.mockReset();});
  it("strictly validates success shape and preserves every database numeric as text",()=>{const parsed=validateStatusResponse(status);expect(parsed.costSchedule?.maximum_modeled_sell_proceeds).toBe("100000");expect(typeof parsed.costSchedule?.version_no).toBe("string");for(const corrupt of [{...status,data:{...status.data,unexpected:true}},{...status,data:{...status.data,costSchedule:{...status.data.costSchedule,version_no:1}}},{...status,data:{...status.data,costSchedule:{...status.data.costSchedule,components:status.data.costSchedule.components.slice(0,3)}}}])expect(()=>validateStatusResponse(corrupt)).toThrow(PersonalRiskClientError);console.log("PASS personal-risk service: strict shapes reject missing/unknown/count/type violations and numeric database values remain strings.");});
  it("uses fixed status query/header placement",async()=>{get.mockResolvedValue({data:status});await getPersonalRiskStatus({observedAt:"2026-09-22T00:00:00Z",pending:{operation:"POLICY_VERSION",idempotencyKey:ID}});expect(get).toHaveBeenCalledWith("/api/personal-risk/bootstrap-status",{params:{observedAt:"2026-09-22T00:00:00Z",operation:"POLICY_VERSION"},headers:{"Idempotency-Key":ID}});});
  it("uses only fixed mutation endpoints, exact bodies, one call and the canonical header",async()=>{post.mockResolvedValueOnce({data:{success:true,data:{policyVersionId:ID,versionNo:"1",replayed:false}}}).mockResolvedValueOnce({data:{success:true,data:{scheduleVersionId:ID,versionNo:"1",replayed:false}}}).mockResolvedValueOnce({data:{success:true,data:{equitySnapshotId:ID,dailyBasisId:ID,weeklyBasisId:ID,dailyEffectiveEquity:"10",weeklyEffectiveEquity:"10",replayed:false}}});await createPolicyVersion(ID);await createCostSchedule(ID);await createEquitySnapshot(ID,{accountEquity:"10",observedAt:"2026-09-22T00:00:00Z",accountValueConfirmed:true,basisTighteningConfirmed:false});expect(post.mock.calls).toEqual([["/api/personal-risk/policy-versions",{confirmed:true},{headers:{"Idempotency-Key":ID}}],["/api/personal-risk/cost-schedules",{confirmed:true},{headers:{"Idempotency-Key":ID}}],["/api/personal-risk/equity-snapshots",{accountEquity:"10",observedAt:"2026-09-22T00:00:00Z",accountValueConfirmed:true,basisTighteningConfirmed:false},{headers:{"Idempotency-Key":ID}}]]);console.log("PASS personal-risk service: fixed allowlisted endpoints, exact bodies, one-shot POSTs and Idempotency-Key-only transport are enforced.");});
});
