import { AlertTriangle, CheckCircle2, DollarSign, LockKeyhole, ShieldCheck, X } from "lucide-react";
import { useCallback, useEffect, useId, useMemo, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import { useDialogFocus } from "../hooks/useDialogFocus";
import { decimalLess, parseEquityDecimal, parseObservation, type ObservationPreview } from "../lib/personalRiskDecimal";
import { clearPendingIntent, readPendingIntent, writePendingIntent, type PersonalRiskOperation, type StoredPendingIntent } from "../lib/personalRiskPendingIntent";
import { createCostSchedule, createEquitySnapshot, createPolicyVersion, getPersonalRiskStatus, PersonalRiskClientError } from "../services/personalRisk";
import type { PersonalRiskStatus } from "../types/personalRisk";

const policyRows = [["Per-position planned loss","0.500000%"],["Aggregate open planned loss","2.000000%"],["Daily gross realized-loss limit","1.000000%"],["Weekly gross realized-loss limit","2.500000%"],["Maximum concurrent positions","5"],["Slippage","25.0000 bps / 0.250000%"],["Time zone","America/New_York"]];
const componentCodes = ["CLOSE_COMMISSION","SEC_REFERENCE","FINRA_TAF_REFERENCE","REGULATORY_ALLOWANCE"];
const failureMessages: Record<string,string> = {
  OWNER_ORIGIN_REQUIRED:"This owner operation is available only from the trusted AzaLens origin.",
  IDEMPOTENCY_CONFLICT:"The saved request key conflicts with a different request. Keep this request frozen and resolve it manually.",
  PERSONAL_RISK_INPUT_INVALID:"The server rejected an input. Correct it and retry with the same saved request key.",
  NUMERIC_PRECISION_INVALID:"A numeric value does not fit the approved precision. Correct its plain-decimal formatting.",
  PERSONAL_RISK_RESPONSE_INVALID:"The response was not safe to interpret. The request key remains pending.",
  PERSONAL_RISK_UNAVAILABLE:"The personal-risk service is unavailable. The request key remains pending.",
  NETWORK_AMBIGUOUS:"The request outcome is ambiguous. Resolve the saved request key before another action.",
};

function Values({ rows }: { rows: string[][] }) { return <dl className="grid gap-2 sm:grid-cols-2">{rows.map(([label,value])=><div key={label} className="rounded-xl border border-stroke bg-surface-soft p-3"><dt className="text-xs text-ink-muted">{label}</dt><dd className="mt-1 break-words font-mono text-sm font-semibold text-ink">{value}</dd></div>)}</dl>; }

function ConfirmDialog({open,title,description,busy,locked,error,onClose,onConfirm,children}:{open:boolean;title:string;description:string;busy:boolean;locked?:boolean;error?:string;onClose:()=>void;onConfirm:()=>void;children:ReactNode}) {
  const ref=useRef<HTMLElement>(null); const titleId=useId(); const descriptionId=useId();
  const safeClose=useCallback(()=>{if(!busy&&!locked)onClose();},[busy,locked,onClose]);
  useDialogFocus({open,dialogRef:ref,onClose:safeClose});
  if(!open)return null;
  return <div className="fixed inset-0 z-[100] grid place-items-end bg-black/60 p-3 backdrop-blur-sm sm:place-items-center" onMouseDown={(event)=>{if(event.target===event.currentTarget)safeClose();}}><section ref={ref} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} tabIndex={-1} className="az-popover max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-3xl p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-brand">Final confirmation</p><h2 id={titleId} className="mt-2 font-display text-2xl font-semibold text-ink">{title}</h2></div><button type="button" aria-label="Close dialog" disabled={busy||locked} onClick={safeClose} className="az-icon-button disabled:opacity-40"><X size={18}/></button></div><p id={descriptionId} className="mt-3 text-sm leading-6 text-ink-muted">{description}</p><div className="mt-5">{children}</div>{error?<div role="alert" className="mt-5 rounded-xl border border-critical/30 bg-critical/10 p-3 text-sm text-critical">{failureMessages[error]??error}</div>:null}<div className="mt-6 flex flex-wrap justify-end gap-3"><Button variant="secondary" disabled={busy||locked} onClick={safeClose}>Cancel</Button><Button disabled={busy||locked} onClick={onConfirm}>{busy?"Submitting…":"Confirm and submit"}</Button></div></section></div>;
}

export default function PersonalRiskSettingsPage(){
  const initial=useMemo(()=>readPendingIntent(),[]); const [status,setStatus]=useState<PersonalRiskStatus|null>(null); const [pending,setPending]=useState<StoredPendingIntent|null>(initial.intent); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(initial.malformed?"Malformed pending recovery data was removed safely.":""); const [error,setError]=useState(""); const [dialog,setDialog]=useState<PersonalRiskOperation|null>(null); const [accountEquity,setAccountEquity]=useState(""); const [observedAt,setObservedAt]=useState(""); const [accountConfirmed,setAccountConfirmed]=useState(false); const [tighteningConfirmed,setTighteningConfirmed]=useState(false); const [preview,setPreview]=useState<ObservationPreview|null>(null); const [previewStatus,setPreviewStatus]=useState<PersonalRiskStatus|null>(null); const previewGeneration=useRef(0);
  const loadStatus=useCallback(async(intent:StoredPendingIntent|null=null,observation?:string)=>{setLoading(true);setError("");try{const next=await getPersonalRiskStatus({observedAt:observation,pending:intent??undefined});setStatus(next);if(intent&&next.pendingIntent?.state==="COMMITTED"){clearPendingIntent();setPending(null);setNotice(`${intent.operation.replaceAll("_"," ")} was confirmed committed.`);const final=await getPersonalRiskStatus({observedAt:observation});setStatus(final);}else if(intent&&next.pendingIntent?.state==="NOT_FOUND")setNotice("No committed result was found. Only a deliberate retry with the same saved request key is available.");return next;}catch(failure){setError(failure instanceof PersonalRiskClientError?failure.code:"NETWORK_AMBIGUOUS");return null;}finally{setLoading(false);}},[]);
  useEffect(()=>{void loadStatus(initial.intent);},[initial.intent,loadStatus]);
  function clearEquityPreview(){previewGeneration.current+=1;setPreview(null);setPreviewStatus(null);setAccountConfirmed(false);setTighteningConfirmed(false);}
  function changeAccountEquity(value:string){setAccountEquity(value);clearEquityPreview();}
  function changeObservedAt(value:string){setObservedAt(value);clearEquityPreview();}
  async function prepareEquity(){setError("");clearEquityPreview();const generation=previewGeneration.current;try{parseEquityDecimal(accountEquity);const parsed=parseObservation(observedAt);const nextPreviewStatus=await getPersonalRiskStatus({observedAt:parsed.normalizedUtc,pending:pending??undefined});if(previewGeneration.current!==generation)return;setPreview(parsed);setPreviewStatus(nextPreviewStatus);setDialog("EQUITY_SNAPSHOT");}catch(failure){if(previewGeneration.current!==generation)return;setError(failure instanceof PersonalRiskClientError?failure.code:failure instanceof Error?failure.message:"PERSONAL_RISK_INPUT_INVALID");}}
  function compareBasis(basis:string|undefined){if(!basis)return {valid:true,tightens:false};try{return {valid:true,tightens:decimalLess(accountEquity,basis)};}catch{return {valid:false,tightens:false};}}
  const dailyComparison=compareBasis(previewStatus?.dailyBasis?.effective_equity); const weeklyComparison=compareBasis(previewStatus?.weeklyBasis?.effective_equity); const comparisonsValid=dailyComparison.valid&&weeklyComparison.valid; const tightDaily=dailyComparison.tightens; const tightWeekly=weeklyComparison.tightens; const tightens=tightDaily||tightWeekly; const tighteningPeriods=tightDaily&&tightWeekly?"daily and weekly":tightDaily?"daily":"weekly";
  async function submit(operation:PersonalRiskOperation){setBusy(true);setError("");let intent=pending;try{if(operation==="EQUITY_SNAPSHOT"&&(!preview||!comparisonsValid||!accountConfirmed||(tightens&&!tighteningConfirmed)))throw new PersonalRiskClientError("PERSONAL_RISK_INPUT_INVALID",400);if(!intent){intent={operation,idempotencyKey:crypto.randomUUID()};writePendingIntent(intent);setPending(intent);}else if(intent.operation!==operation)throw new PersonalRiskClientError("IDEMPOTENCY_CONFLICT",409);if(operation==="POLICY_VERSION")await createPolicyVersion(intent.idempotencyKey);else if(operation==="COST_SCHEDULE")await createCostSchedule(intent.idempotencyKey);else await createEquitySnapshot(intent.idempotencyKey,{accountEquity,observedAt:preview!.normalizedUtc,accountValueConfirmed:true,basisTighteningConfirmed:tightens});const resolved=await loadStatus(intent,preview?.normalizedUtc);if(resolved?.pendingIntent?.state==="NOT_FOUND")setError("NETWORK_AMBIGUOUS");else{setDialog(null);setAccountEquity("");setObservedAt("");setAccountConfirmed(false);setTighteningConfirmed(false);setPreview(null);setPreviewStatus(null);}}catch(failure){setError(failure instanceof PersonalRiskClientError?failure.code:"NETWORK_AMBIGUOUS");}finally{setBusy(false);}}
  const canRetry=Boolean(pending&&status?.pendingIntent?.state==="NOT_FOUND"); const policyReady=!status?.policyVersion&&!pending; const scheduleReady=Boolean(status?.policyVersion&&!status?.costSchedule&&!pending); const equityReady=Boolean(status?.policyVersion&&status?.costSchedule&&!pending);
  return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-6xl px-4 py-7 pb-24 sm:px-6 lg:px-8"><header className="mb-7"><Link to="/settings" className="text-sm font-semibold text-brand hover:underline">Settings</Link><h1 className="mt-2 font-display text-3xl font-semibold text-ink">Personal risk controls</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-ink-muted">Create and review immutable owner-only risk foundations. Each step commits separately; this page never places trades or writes the outcome ledger.</p></header><div aria-live="polite" role="status" className="mb-5 min-h-6 text-sm text-ink-muted">{loading?"Loading authoritative personal-risk status…":notice}</div>{error?<div role="alert" className="mb-5 rounded-2xl border border-critical/30 bg-critical/10 p-4 text-sm text-critical">{failureMessages[error]??error}</div>:null}
  {pending?<Card className="mb-6"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-caution"/><div><h2 className="font-semibold text-ink">Pending request recovery</h2><p className="mt-1 text-sm text-ink-muted">{pending.operation.replaceAll("_"," ")} is frozen to its saved idempotency key. No financial body or credential was stored.</p>{pending.operation==="EQUITY_SNAPSHOT"?<p className="mt-2 text-sm font-medium text-caution">Re-enter every equity field and confirm it again before a same-key retry.</p>:null}<div className="mt-3 flex flex-wrap gap-3"><Button variant="secondary" disabled={loading||busy} onClick={()=>void loadStatus(pending)}>Resolve status</Button>{canRetry?<Button disabled={busy} onClick={()=>pending.operation==="EQUITY_SNAPSHOT"?void prepareEquity():setDialog(pending.operation)}>Retry same request key</Button>:null}</div></div></div></Card>:null}
  <div className="grid gap-6 lg:grid-cols-3"><Card><div className="mb-4 flex items-center gap-2 text-brand"><ShieldCheck size={18}/><h2 className="font-display text-lg font-semibold text-ink">1. Policy version</h2></div><Values rows={policyRows}/><p className="mt-4 text-sm text-ink-muted">{status?.policyVersion?`Version ${status.policyVersion.version_no} is immutable and active.`:"No policy version exists."}</p><Button className="mt-4 w-full" disabled={!policyReady||loading} onClick={()=>setDialog("POLICY_VERSION")}>{status?.policyVersion?"Policy already created":"Create policy version"}</Button></Card>
  <Card><div className="mb-4 flex items-center gap-2 text-brand"><LockKeyhole size={18}/><h2 className="font-display text-lg font-semibold text-ink">2. Cost schedule</h2></div><Values rows={[["Broker","Saxo Bank"],["Tier / currency","Classic / USD"],["Scope","LONG_US_LISTED_CASH_EQUITY"],["Effective","2026-09-19"],["Maximum proceeds","$100,000"],["Maximum quantity","10,000"]]}/><ul className="mt-4 space-y-1 font-mono text-xs text-ink-muted">{componentCodes.map(code=><li key={code}>• {code}</li>)}</ul><p className="mt-3 text-xs text-ink-muted">Saxo Bank is the name printed on the owner’s account documents; the account agreement’s contracting-entity clause has not been verified. Broker, regulator and founder evidence classifications remain distinct. Historical realized fees are not predictive components.</p><Button className="mt-4 w-full" disabled={!scheduleReady||loading} onClick={()=>setDialog("COST_SCHEDULE")}>{status?.costSchedule?`Schedule version ${status.costSchedule.version_no}`:"Create cost schedule"}</Button></Card>
  <Card><div className="mb-4 flex items-center gap-2 text-brand"><DollarSign size={18}/><h2 className="font-display text-lg font-semibold text-ink">3. Equity snapshot</h2></div>{status?.equitySnapshot?<p className="mb-4 rounded-xl bg-positive/10 p-3 text-sm text-positive"><CheckCircle2 className="mr-2 inline" size={16}/>Latest: ${status.equitySnapshot.account_equity} USD at {status.equitySnapshot.observed_at}</p>:<p className="mb-4 text-sm text-ink-muted">No broker equity snapshot exists.</p>}<label className="block text-sm font-semibold text-ink" htmlFor="account-equity">Total broker-confirmed USD account equity</label><input id="account-equity" inputMode="decimal" value={accountEquity} onChange={event=>changeAccountEquity(event.target.value)} placeholder="Plain decimal, no commas" className="mt-2 min-h-12 w-full rounded-xl border border-stroke bg-surface-soft px-3 text-ink"/><p className="mt-2 text-xs leading-5 text-ink-muted">Not cash, buying power, position market value or cost basis.</p><label className="mt-4 block text-sm font-semibold text-ink" htmlFor="observed-at">Exact broker observation time</label><input id="observed-at" value={observedAt} onChange={event=>changeObservedAt(event.target.value)} placeholder="2026-09-21T20:00:37+05:00" className="mt-2 min-h-12 w-full rounded-xl border border-stroke bg-surface-soft px-3 font-mono text-sm text-ink"/><Button className="mt-4 w-full" disabled={!equityReady||loading} onClick={()=>void prepareEquity()}>{status?.equitySnapshot?"Record fresh snapshot":"Review first snapshot"}</Button></Card></div>
  <Card className="mt-6"><h2 className="mb-4 font-display text-lg font-semibold text-ink">Current basis state</h2><Values rows={[["Daily basis",status?.dailyBasis?`$${status.dailyBasis.effective_equity} (sequence ${status.dailyBasis.basis_sequence})`:"Not established"],["Weekly basis",status?.weeklyBasis?`$${status.weeklyBasis.effective_equity} (sequence ${status.weeklyBasis.basis_sequence})`:"Not established"],["New York date",status?.observation.newYorkDate??"—"],["Monday-based week",status?.observation.newYorkWeek??"—"]]}/></Card>
  <ConfirmDialog open={dialog==="POLICY_VERSION"} title="Create immutable policy version 1?" description="Changing any value later requires a new policy version." busy={busy} error={error} onClose={()=>setDialog(null)} onConfirm={()=>void submit("POLICY_VERSION")}><Values rows={policyRows}/></ConfirmDialog>
  <ConfirmDialog open={dialog==="COST_SCHEDULE"} title="Create the Saxo Bank Classic schedule?" description="This independently creates the approved four-component predictive schedule. The broker name is copied from account documents; the contracting-entity clause remains unverified." busy={busy} error={error} onClose={()=>setDialog(null)} onConfirm={()=>void submit("COST_SCHEDULE")}><Values rows={[["Broker name on documents","Saxo Bank"],["Components",componentCodes.join(", ")],["Evidence","Broker / regulator / founder classified references"]]}/></ConfirmDialog>
  <ConfirmDialog open={dialog==="EQUITY_SNAPSHOT"} title="Record broker equity evidence?" description="This is a repeatable evidence event. The server determines authoritative bases." busy={busy} error={error} onClose={()=>setDialog(null)} onConfirm={()=>void submit("EQUITY_SNAPSHOT")}><Values rows={[["Proposed equity",accountEquity?`$${accountEquity}`:"Re-entry required"],["Normalized UTC",preview?.normalizedUtc??"—"],["Reference preview",preview?.confirmationReference??"—"],["New York date",preview?.newYorkDate??"—"],["New York week",preview?.newYorkWeek??"—"],["Current daily basis",previewStatus?.dailyBasis?.effective_equity??"Not established"],["Resulting daily basis",tightDaily?accountEquity:previewStatus?.dailyBasis?.effective_equity??accountEquity],["Current weekly basis",previewStatus?.weeklyBasis?.effective_equity??"Not established"],["Resulting weekly basis",tightWeekly?accountEquity:previewStatus?.weeklyBasis?.effective_equity??accountEquity]]}/>{tightens?<div className="mt-4 rounded-xl border border-caution/35 bg-caution/10 p-4 text-sm text-caution"><strong>Basis tightening:</strong> {tighteningPeriods}. It cannot be raised again during that period.</div>:null}<label className="mt-4 flex gap-3 text-sm text-ink"><input type="checkbox" checked={accountConfirmed} onChange={event=>setAccountConfirmed(event.target.checked)}/>I confirm this is total broker-confirmed USD account equity.</label>{tightens?<label className="mt-3 flex gap-3 text-sm text-ink"><input type="checkbox" checked={tighteningConfirmed} onChange={event=>setTighteningConfirmed(event.target.checked)}/>I understand and confirm irreversible basis tightening for this period.</label>:null}</ConfirmDialog>
  </main>;
}
